# Generated by Django 5.2.2 on 2025-06-07 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_nhoexz', max_length=255, verbose_name='image'),
        ),
    ]
