# Generated by Django 5.2.2 on 2025-06-07 08:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1749283799/Screenshot_2025-06-05_094214_u0kkry', max_length=255, null=True, verbose_name='image'),
        ),
    ]
